adding-react-router-and-setup-pages-and-components-folder
Stella-Events/event-hive pull request #5
Opened 2024-07-08 23:16 UTC by rtdongullo

2024-07-08 23:27 UTC, mickeymond commented
@rtdongullo Nice one for being able to raise your PR and asking for my review.
However, I have handed over the review to @AJ-Appiah instead.

2024-07-09 06:47 UTC, rtdongullo commented
@mickeymond  Well noted with thanks.

2024-07-09 09:13 UTC, AJ-Appiah requested changes
Check the function App() placement, 
No closing and opening tag around;
  return (
    <>
 <RouterProvider router={router} />
    </>

2024-07-09 11:09 UTC, AJ-Appiah approved these changes

2024-07-09 11:10 UTC, merged